apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-deployment
  labels:
    app: hellok8s
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - name: hellok8s
          image: 'microservicesample.azurecr.io/gregorbiswanger/hellokubernetes:861'
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: hellok8s

---
apiVersion: v1
kind: Service
metadata:
  name: hellok8s-deployment-service
  labels:
    name: hellok8s-deployment-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hellok8s
  type: LoadBalancer